### ISSUE TITLE
Arizone timezone is not included

### ISSUE THREAD

**Issue by iarcones** [ealong/Trilogy-Tutor-Auto-Emailer#1]
I just added this: 

<**elif 'Arizona' in student_tz:
	tz = timezone('US/Arizona')**>
It worked.

Thanks so much, it helps a lot :-)

**Comment by dwsosa** [comment]
The code relies on the tz column on the google sheet to match one of the below conditions:

```tz = ""	
			if 'CST' in student_tz:
				tz = timezone('US/Central')
			elif 'EST' in student_tz:
				tz = timezone('US/Eastern')
			elif 'MST' in student_tz:
				tz = timezone('US/Mountain')
			elif 'PST' in student_tz:
				tz = timezone('US/Pacific')
```

**Comment by ealong** [comment]
Ah, the 5th US timezone: Arizona (Arizona doesn't observe DST). I'll include this one in my next update. Thanks Isabel!

**Comment by ealong** [comment]
Added:

`elif 'ARZ' in student_tz:
                tz = timezone('US/Arizona')`
