### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by iarcones** [ealong/Trilogy-Tutor-Auto-Emailer#3]
it was working perfectly until today
```
  File "app.py", line 182
    print(f"Email {student_email} not found. If you know who this is, please supply the email address they registered with or enter 'skip' to skip to the next session.")
                                                                                                                                                                       ^
SyntaxError: invalid syntax
```

**Comment by ealong** [comment]
Hmmm, I just ran it and it worked perfectly for me... Try pulling from the repo again.

If that doesn't work, could you paste some more code from before and after that section?

**Comment by MalinkaMell** [comment]
Happened to me with Python 2.7.
Works fine with version 3.8

**Comment by ealong** [comment]
Ah, that must be it. Python f-strings were introduced in 3.0 - [link](https://www.geeksforgeeks.org/formatted-string-literals-f-strings-python/)
